### Using this file to visualize the data generated by "Simulation.R"
### If users break the file naming rule during customization, they would also need to adjust the codes here to make the programme valid.

remove(list=ls())
setwd("Set your own work direction")
library(ggplot2)
library(gridExtra)
library(xlsx)
library(openxlsx)
library(readxl)
library(paletteer)

options(scipen = 100)
number_of_polulation <- 6
mr_gradient <- c(0,10^(-7:-2))
target_terms <- c("Biomass","Existence","Osci","Biomass_var",
                  "Existence_var","Osci_var")
target_terms2 <- c("Biomass","Species diversity","Temporal Instability","Patchiness",
                   "Species aggregation","CV of\ntemporal instability")
par_df <- expand.grid(seq(0.25,2,by = 0.25),seq(0.25,2,by = 0.25))
colnames(par_df) <- c("beta1","beta2")
for (i in 1:length(target_terms)) {
  for (j in 1:length(mr_gradient)) {
    assign(paste("df",target_terms2[i], log10(mr_gradient[j]),sep = "_"),
           read_xlsx(paste(number_of_polulation,"Gamma",
                           paste("mr=",mr_gradient,collapse = " "),
                           target_terms[i],".xlsx",sep="_"), 
                     sheet = paste0("mr=",log10(mr_gradient[j])), col_names  = FALSE))
    assign(paste("df",target_terms2[i],log10(mr_gradient[j]), sep = "_"), 
           get(paste("df",target_terms2[i],log10(mr_gradient[j]), sep = "_"))[,-1])
    assign(paste("df",target_terms2[i],log10(mr_gradient[j]), sep = "_"), 
           cbind(par_df, get(paste("df",target_terms2[i],log10(mr_gradient[j]), sep = "_"))))
  }
}

for (i in 1:length(target_terms2)) {
  if(i <= 3){
    for (j in 1:length(mr_gradient)) {
      df <- get(paste("df",target_terms2[i],log10(mr_gradient[j]), sep = "_"))
      df$mean <- rowMeans(df[,3:52])
      df$se <- 0
      for (ii in 1:nrow(df)) {
        df$se[ii] <- sd(df[ii,3:52])/length(df[ii,3:52]) 
      }
      assign(paste("df",target_terms2[i],log10(mr_gradient[j]), sep = "_"), df)
    }
  }else{
    for (j in 1:length(mr_gradient)) {
      df <- get(paste("df",target_terms2[i],log10(mr_gradient[j]), sep = "_"))
      df[,3:52] <- df[,3:52]/get(paste("df",target_terms2[i-3],log10(mr_gradient[j]), sep = "_"))[,3:52]
      df[is.na(df)] <- 0
      df$mean <- rowMeans(df[,3:52])
      df$se <- 0
      for (ii in 1:nrow(df)) {
        df$se[ii] <- sd(df[ii,3:52])/length(df[ii,3:52]) 
      }
      assign(paste("df",target_terms2[i],log10(mr_gradient[j]), sep = "_"), df)
    }
  }
}
options(scipen = 0)


for (i in 1:length(target_terms2)) {
  final_df_parspan = data.frame()
  for (j in 1:length(mr_gradient)) {
    df <- get(paste("df",target_terms2[i],log10(mr_gradient[j]), sep = "_"))
    df <- df[,c(1,2,ncol(df)-1,ncol(df))]
    df$Dr <- mr_gradient[j]
    final_df_parspan <- rbind(final_df_parspan, df)
  }
  assign(paste0("myParSpan",i), ggplot(final_df_parspan, aes(beta1, beta2, fill = log(mean)))+
           geom_tile(color = "white", size = 0.25)+
           scale_fill_gradient(low = "black", high = "white", name = paste0("log(",target_terms2[i],")"))+
           labs(x = expression("\u03B21"), y = expression("\u03B22"))+
           facet_wrap(~Dr, labeller = labeller(Dr = as_labeller(function(value){
             return(paste0("D =", value))
           })))+
           theme_classic()
  )
}


for (i in 1:length(target_terms2)) {
  final_df = data.frame()
  for (j in 1:length(mr_gradient)) {
    df <- get(paste("df",target_terms2[i],log10(mr_gradient[j]), sep = "_"))
    df <- df[,c(1,2,ncol(df)-1,ncol(df))]
    df$pars <- log(df$beta1 + 0.1*df$beta2)
    df$Dr <- mr_gradient[j]
    final_df <- rbind(final_df, df)
  }
  #final_df$Dr <- factor(final_df$Dr, level = paste(log10(mr_gradient)))
  assign(paste0("myLineChart",i),ggplot(final_df, aes(Dr, mean, group = beta2, color = beta2))+
           geom_point(aes(group = pars))+
           geom_line()+
           scale_y_log10()+
           scale_x_log10()+
           geom_errorbar(aes(ymin = mean - se, ymax = mean + se, color = beta2),width = 0.2) +
           labs(x = "Dispersal rate", y = target_terms2[i])+
           facet_wrap(~beta1, labeller = as_labeller(function(value) {
             return(paste("\u03B21 = ", value))
           })) +
           # facet_wrap(~beta1, labeller = labeller(beta1 = as_labeller(function(value) {
           #   paste("\u03B2\u2081 =", value)
           # }))) +
           labs(color = expression(beta[2])) +
           theme_classic() + 
           theme(legend.title = element_text(hjust = 0.2))
)
}

Exist_Linechart <- grid.arrange(myLineChart2 + ggtitle("a")+theme(plot.title = element_text(size = 16)),
                                myLineChart5 + ggtitle("b")+theme(plot.title = element_text(size = 16)),
                                nrow = 1)

ggsave(filename = paste0("./graphs/N=",number_of_polulation,"_Exist_lineChart.pdf"),
       plot = Exist_Linechart,
       width = 11,
       height = 5,
       dpi = 1000)

Biomass_Linechart <- grid.arrange(myLineChart1 + ggtitle("a")+theme(plot.title = element_text(size = 16)),
                                  myLineChart4 + ggtitle("b")+theme(plot.title = element_text(size = 16)),
                                  nrow = 1)

ggsave(filename = paste0("./graphs/N=",number_of_polulation,"_Biomass_lineChart.pdf"),
       plot = Biomass_Linechart,
       width = 11,
       height = 5,
       dpi = 1000)

Osci_Linechart <- grid.arrange(myLineChart3 + ggtitle("a")+theme(plot.title = element_text(size = 16)),
                               myLineChart6 + ggtitle("b")+theme(plot.title = element_text(size = 16)),
                               nrow = 1)

ggsave(filename = paste0("./graphs/N=",number_of_polulation,"_Osci_lineChart.pdf"),
       plot = Osci_Linechart,
       width = 11,
       height = 5)




